### ISSUE TITLE
Customization HowTo

### ISSUE THREAD

**Issue by RoelofBerg** [UDOOboard/mkudoobuntu#13]
Hi,

great work, thanks. I want to customize the image and wonder what would be the best way (aligned to the tool's philosophy) to:

a) Customize the kernel parameters (make menuconfig)
b) Customize the device tree
c) Develop (and later use) our own kernel driver module

Any suggestions ? (I know how to do this tasks on a vanilla system. However, I wonder how to best align this to the tool - instead of crudely hacking my own way.)

Thanks,
Roelof

**Comment by fmntf** [comment]
Hi. The kernel, modules and dtbs are installed from a debian package coming from the repository (linux-udooqdl or linux-udooneo). 

You can create your own kernel packages and publish them on your own repo, then adding the repo as an overlay over the others (see debootstrap.sh).
Or more simply, just unstall your own kernel at the end of the debootstrap and hold the package in order to prevent unwanted upgrades.
