### ISSUE TITLE
udoobunto v2 Beta - does not recognize my HDMI monitor

### ISSUE THREAD

**Issue by deltabert** [UDOOboard/mkudoobuntu#5]
Hi all,
Just installed udoobuntu's latest release but i am not able to set the correct monitor configuration.
It uses a different way of configuration as udoobunto v1.
Ti boots with a default config of (sudo xrandr: V:640x480p-60    60.0*+   )
How can i set the resolution to 1920 x 1080 ?

Please is there any help on this?

Kind regards, Bert

**Comment by fmntf** [comment]
Hi, which board are you using?
Quad/Dual are using HDMI from the SoC, Neo boards have an external chip, and things work a lot differently.

**Comment by deltabert** [comment]
Tanks for commune back On mt issue.
Sorry, i should have mentioned this. It's a Quad. With other OS-es the Video HDMI works fust fine.

**Comment by macharborguy** [comment]
I am having the same issue with my Udoo Quad (I backed the original Kickstarter campaign).

Udoobuntu 1 (Ubuntu 12) worked fine, but I was unable to use Electron (a framework for making desktop style apps using NodeJS) due to how old the distro is, apparently.  Part of it may be due to Chromium only being version 18 maximum in Ubuntu 12.04, but all the way to version 48+ in 14.04

I reflashed to Udoobuntu RC1 for my Quad, and it is unable to properly talk to my HDTV via HDMI (I get a No Signal message on my 32" RCA HDTV)  Model number of the HDTV is 32LB45RQ

I was able to get video by using a work around that is available on the forums, adding the following line to my uEnv.txt file in /boot...

`video=video=mxcfb0:dev=hdmi,1920x1080M@30,if=RGB24`

the problem is I dont actually get 30fps, but 24fps instead, so the whole UI feels very sluggish due to the low frame rate.

Flashing back to Ubuntu 12 does not give me the same issue

I also noticed in Udoobuntu 2 RC1, is that the available memory is around 1002MB, rather than the default in 12.04 which allocated 128MB to video memory.  Even manually allocating memory by adding...

`mem=768M`

doesnt appear to help anything other that lower my main physical memory

I also noticed that the Udoo Configuration Utility is not present in Udoobuntu 2 RC1, so there is no easy way to make the adjustments i could make in the older version of Udoobuntu

**Comment by deltabert** [comment]
@macharborguy 

Thank you for your hint to use uEnv.txt, for adding boot options.
Using the command xandr -q I found out that the display name is DISP3 BG

In /boot/uEnv.txt i tried several display options and this is the one that works fine now:
video='DISP3 BG':1920x1200@60
(Notice the single quotes because there was a space in the display name.)

BTW, my display is an Samsung SyncMaster 2443BW, which has a DVI input. The cable i use is a HDMI-DVI cable. This combination worked just fine with Lubuntu for UDOO, There the display was beautifully recognized with all its resolutoin modes.

Now with the use of the parms in uEnv.txt, UdooBuntu v2 rc1 recognizes also all display resolution modes from my display. 

Do'nt ask why, just take advantage of it...

Regards, Bert
